
long_short_name_map = {
                        # magi
                        "a water weird" : "weird",
                        # ratting
                        "a young rat" : "rat",
                        "a baby rat" : "rat",
                        "a black rat" : "rat",
                        "an old rat" : "rat",
                        "a rat" : "rat",
                        # Cyrene
                        "Bruggio, the Blacksmith" : "bruggio",
                        "a pretty young girl" : "Fantine",
                        "an ice mage" : "mage",
                        "an imperial guardsman" : "guardsman",
                        "an oscillating lake wyrm" : "wyrm",
                        "a mountain archer" : "archer",
                        "a runic knight" : "knight",
                        "an aklan servitor" : "servitor",
                        "an elderly woman" : "paloma",
                        "an aklan servitor" : "servitor",
                        "Rodwin, a young travelling food seller" : "rodwin",
                        # Creville
                        "a delirious receptionist" : "receptionist",
                        "a restrained nurse" : "nurse",
                        "a bloated female cockroach" : "cockroach",
                        "a burly troll dweller" : "dweller",
                        "a swarm of black flies" : "flies",
                        "an axe-wielding dwarven patient" : "patient",
                        "a fleshy white maggot" : "maggot",
                        "a grinning imp" : "imp",
                        "a massive rat snake" : "snake",
                        "a long-tailed weasel" : "weasel",
                        "a great horned owl" : "owl",
                        "a hulking bush of hogsweed" : "hogsweed",
                        "an enormous black rat" : "rat",
                        "a great aphid" : "aphid",
                        "a doctor with numerous facial wounds" : "doctor",
                        "an injured maid" : "maid",
                        "a terror-stricken nurse" : "nurse",
                        "a blind, knife-wielding woman" : "woman",
                        "a blood-spattered jester" : "jester",
                        "Suire, a mauled, narcissistic siren" : "suire",
                        "Villinix, the herbalist" : "villinix",
                        "Ulthor, the coroner" : "ulthor",
                        "a crawling Tsol'aa inmate" : "inmate",
                        "a maniacal atavian inmate" : "inmate",
                        "a beaten prisoner" : "prisoner",
                        "a deranged rajamalan dweller" : "dweller",
                        "a shady dealer" : "dealer",
                        "Villinix, the herbalist" : "villinix",
                        }

